env:
  global:
      # Set these values
      - BUILD_COMMIT="4.7.0" # "master"
      - PYPI_UPLOAD=true # true or false
      - TESTPYPI_UPLOAD=false
      - CONDA_BUILD=false
      - CONDA_UPLOAD=false
      # These values should not usually change
      - REPO_DIR="arch"
      - PLAT=x86_64
      - UNICODE_WIDTH=32
      - BUILD_DEPENDS="Cython numpy cached_property wheel==0.31.1"
      - TEST_DEPENDS="numpy scipy pandas pytest nose cached_property wheel==0.31.1 "
      - PLAT=x86_64
      - UNICODE_WIDTH=32
      - CONDA_NUMPY_VERSION=1.15
      - SDIST=false

language: python
python: 3.6
sudo: required
dist: trusty
services: docker

matrix:
  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - UNICODE_WIDTH=16
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - PLAT=i686
        - UNICODE_WIDTH=16
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - PLAT=i686        
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.5
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.7

before_install:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT
    - source build-conda.sh
    - source build-sdist.sh

after_success:
    # Upload wheels/sdist to PyPI
    - source twine-upload.sh