package:
    name: arch
    version: 4.6.0
source:
    version: 4.6.0
    git_url: 'https://github.com/bashtage/arch.git'
build:
    number: 0
requirements:
    build:
        - python
        - setuptools
        - cython
        - 'numpy x.x'
        - scipy
        - statsmodels
    run:
        - python
        - 'numpy x.x'
        - scipy
        - statsmodels        
test:
    requires:
        - pytest
        - nose
about:
    home: 'https://github.com/bashtage/arch'
    license: NSCA
