{% set name = "arch" %}
{% set version = "4.8.1" %}
{% set sha = "d56fe5341f3a3294477f677e16000d2e283fd110fb1f1d3d4c27046b1f988797" %}
package:
    name: {{ name|lower }}
    version:  {{ version }}

source:
    version: {{ version }}
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha }}
    # url: https://github.com/bashtage/{{ name }}/archive/{{ version }}.tar.gz

build:
    number: 0
    script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - {{ compiler('c') }}    
    host:
        - python
        - pip
        - cython
        - numpy
        - scipy
        - statsmodels
        - wheel
    run:
        - python
        - cython
        - {{ pin_compatible('numpy') }}
        - scipy
        - statsmodels        

test:
    requires:
        - pytest
        - nose
    imports:
        - arch        

about:
    home: 'https://github.com/bashtage/arch'
    license: NCSA
    license_file: LICENSE.md
    summary: ARCH (volatility) model and more
