{% set name = "arch" %}
{% set version = "4.13" %}
{% set sha = "062b8541ee4043410db1e3fce9720e414505edff3d49a784179957726cd7b25d" %}
package:
    name: {{ name|lower }}
    version:  {{ version }}

source:
    version: {{ version }}
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha }}

build:
    number: 0
    script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - {{ compiler('c') }}    
    host:
        - python
        - pip
        - cython>=0.29
        - numpy>=1.14
        - scipy>=1
        - statsmodels>=0.9
        - wheel
        - pandas>=0.23
    run:
        - python
        - cython>=0.29
        - {{ pin_compatible('numpy') }}
        - scipy>=1
        - statsmodels>=0.9
        - pandas>=0.23

test:
    requires:
        - pytest
        - nose
    imports:
        - arch        

about:
    home: 'https://github.com/bashtage/arch'
    license: NCSA
    license_file: LICENSE.md
    summary: ARCH (volatility) model and more
