{% set name = "arch" %}
{% set version = "4.8.0" %}
{% set sha = "fec0f68c38f5b6dbc1493c1eac85fe4aa3e3645d970b42190521a9f358ab0581" %}
package:
    name: {{ name|lower }}
    version:  {{ version }}

source:
    version: {{ version }}
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha }}
    # url: https://github.com/bashtage/{{ name }}/archive/{{ version }}.tar.gz

build:
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
    build:
        - {{ compiler('c') }}    
    host:
        - python
        - pip
        - cython
        - numpy
        - scipy
        - statsmodels
    run:
        - python
        - cython
        - {{ pin_compatible('numpy') }}
        - scipy
        - statsmodels        

test:
    requires:
        - pytest
        - nose
    imports:
        - arch        

about:
    home: 'https://github.com/bashtage/arch'
    license: NCSA
    license_file: LICENSE.md
    summary: ARCH (volatility) model and more
